window.LOCAL_MAP_API_KEY = "MY_LOCAL_MAP_API_KEY";
window.LOCAL_GROOM_NAME = "MY_GROOM_NAME";
window.LOCAL_BRIDE_NAME = "MY_BRIDE_NAME";
window.LOCAL_GROOM_NAME_EN = "MY_GROOM_NAME_EN";
window.LOCAL_BRIDE_NAME_EN = "MY_BRIDE_NAME_EN";
