window.LOCAL_MAP_API_KEY = "MY_LOCAL_MAP_API_KEY";
window.LOCAL_GROOM_NAME = "MY_GROOM_NAME";
window.LOCAL_BRIDE_NAME = "MY_BRIDE_NAME";
window.LOCAL_GROOM_NAME_EN = "MY_GROOM_NAME_EN";
window.LOCAL_BRIDE_NAME_EN = "MY_BRIDE_NAME_EN";
window.LOCAL_GROOM_ACC = "MY_GROOM_ACC";
window.LOCAL_BRIDE_ACC = "MY_BRIDE_ACC";
// 혼주정보
window.LOCAL_GROOM_DAD_NAME = "MY_GROOM_DAD_NAME";
window.LOCAL_GROOM_DAD_ACC 	= "MY_GROOM_DAD_ACC";
window.LOCAL_GROOM_MOM_NAME = "MY_GROOM_MOM_NAME";
window.LOCAL_GROOM_MOM_ACC 	= "MY_GROOM_MOM_ACC";

window.LOCAL_BRIDE_DAD_NAME = "MY_BRIDE_DAD_NAME";
window.LOCAL_BRIDE_DAD_ACC 	= "MY_BRIDE_DAD_ACC";
window.LOCAL_BRIDE_MOM_NAME = "MY_BRIDE_MOM_NAME";
window.LOCAL_BRIDE_MOM_ACC 	= "MY_BRIDE_MOM_ACC";

